name: my_first_app
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11

  # Puedes agregar más dependencias aquí si las necesitas,
  # pero deben ser compatibles con Dart 3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1  # Esta versión es compatible con Dart 3.8.0

flutter:
  uses-material-design: true

