// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzC7hvUIitPW2k4lr_YmXELSMETHtFFjI',
    appId: '1:956695124445:web:e1541d2a071d2ad6b43e34',
    messagingSenderId: '956695124445',
    projectId: 'pideya-7aacb',
    authDomain: 'pideya-7aacb.firebaseapp.com',
    storageBucket: 'pideya-7aacb.firebasestorage.app',
    measurementId: 'G-NH1994P1YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg_WqxiRwoQVbvjKvHSHLgEX7m_wj57Rc',
    appId: '1:956695124445:android:3d0b549ed21b1d7fb43e34',
    messagingSenderId: '956695124445',
    projectId: 'pideya-7aacb',
    storageBucket: 'pideya-7aacb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuzDxJ9WrkWvFsdpgI5YZ7dpi8O3zX4x0',
    appId: '1:956695124445:ios:6f7d5f0ac50665f5b43e34',
    messagingSenderId: '956695124445',
    projectId: 'pideya-7aacb',
    storageBucket: 'pideya-7aacb.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuzDxJ9WrkWvFsdpgI5YZ7dpi8O3zX4x0',
    appId: '1:956695124445:ios:6f7d5f0ac50665f5b43e34',
    messagingSenderId: '956695124445',
    projectId: 'pideya-7aacb',
    storageBucket: 'pideya-7aacb.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzC7hvUIitPW2k4lr_YmXELSMETHtFFjI',
    appId: '1:956695124445:web:a2417f22291b71a2b43e34',
    messagingSenderId: '956695124445',
    projectId: 'pideya-7aacb',
    authDomain: 'pideya-7aacb.firebaseapp.com',
    storageBucket: 'pideya-7aacb.firebasestorage.app',
    measurementId: 'G-37NKFJXRSL',
  );
}
